# Simple NATS server configuration for local development.
# Listen on default port 4222. Additional options can be added as needed.
port: 4222
# By default NATS allows anonymous connections and binds to all interfaces.
# Adjust settings here if you want to restrict access or enable authentication.

mqtt {
  port:1833
}

jetstream: enabled